### PR TITLE
Deployments: Principles for deploying changes

### PR DESCRIPTION
**Pull request by nottrobin**
Start a document to explain some important princilpes around when
to release changes to our projects:

- Master branch is always releasable (this has been a principle for years, but I'm finally writing it down)
- No risky releases on a Friday (this is new, and came out of https://portal.admin.canonical.com/C113582/)

### CODE REVIEW

**Comment by barrymcgee** [comment]
LGTM 👍🏻

**Comment by deadlight** [comment]
Formal clarification of releasable master rule :+1: 

Cautious Fridays (like Casual Fridays but different) :+1:

**Comment by anthonydillon** [comment]
:+1:

**Comment by nottrobin** [comment]
Since filing this, I realised there was already a `deploy.md`, and decided it would be a little neater to add to that instead of creating a new document. Please take another look and check you're happy with this new structure?

**Comment by anthonydillon** [comment]
Still :+1:

**Comment by deadlight** [comment]
👍

**Comment by tbille** [comment]
still :+1:

**Pull request merged**
