### PR TITLE
Add Fibonacci estimation guide

### PR DESCRIPTION
**Pull request by anthonydillon**
Created a Fibonacci estimation guide document.

_Plan to add dev/UX/ design examples in time_

### CODE REVIEW

**Comment by nottrobin** [comment]
Should this wait until you add some examples? Or would you rather merge this first and add examples later?

I do want to make sure examples are added, because I think most of the words used here are very much open to interpretation without some concrete examples.

**Comment by anthonydillon** [comment]
Yes I would like to follow up with examples. Should be able to pick a few
from the trans planning this iteration.

**Comment by anthonydillon** [comment]
https://github.com/canonical-webteam/practices/issues/35

**Comment by nottrobin** [comment]
Okay :+1: for now

**Comment by Lukewh** [comment]
👍

**Comment by WillMoggridge** [comment]
👍

**Comment by anthonydillon** [comment]
Thanks all!

**Pull request merged**
