### PR TITLE
Content tweaks on server-side-frameworks

### PR DESCRIPTION
**Pull request by nottrobin**
Just 2 tiny improvements from https://github.com/canonical-webteam/practices/pull/97#pullrequestreview-177144223

### CODE REVIEW

**Comment by anthonydillon** [comment]
@barrymcgee why have you approved and merged this change? PRs should have at least two :+1: and has been active for 24 hours.

**Comment by nottrobin** [comment]
@anthonydillon yes but this is just 2 very small tweaks on top of https://github.com/canonical-webteam/practices/pull/97 which was already approved and merged. It didn't effect the actual meaning of the content at all. I think what @barrymcgee did was reasonable (and I plan to update CONTRIBUTING.md to reflect this).

**Comment by barrymcgee** [comment]
@anthonydillon These are essentially two typos.. as per Kit's comment on the PR Review thread which I co-incidentally just read before this; 

_"the general consensus seemed to be that it would be helpful to allow for code-review approval with minor changes requested"_

**Comment by anthonydillon** [comment]
@barrymcgee Agree thanks :+1:

**Pull request merged**
